### ISSUE TITLE
Implement fast parallel version of scipy.interpolate.LinearNDInterpolator

### ISSUE THREAD

**Issue by vovaf709** [neuro-ml/imops#20]
[scipy.interpolate.LinearNDInterpolator](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.LinearNDInterpolator.html#scipy.interpolate.LinearNDInterpolator) inference consists of 2 steps:
- Delaunay triangulation (slowest step)
- Linear barycentric interpolation on each triangle (easier to implement)

**Comment by alexeybelkov** [comment]
The development is currently here: https://github.com/alexeybelkov/parinterp

**Comment by vovaf709** [comment]
closed by #48
