### ISSUE TITLE
skimage morphology benchmarks

### ISSUE THREAD

**Issue by ogencoglu** [neuro-ml/imops#43]
Awesome work!

You have benchmarks of scipy and Cython backends for binary morphology ops. Does scipy here correspond to scikit-image? If not, do you know how scikit-image performs in those operations?

**Comment by vovaf709** [comment]
Thanks :) Yea, `Scipy` backend for morphology ops correspond to `scikit-image`.

Actually in the `imops`we do not distinguish between `scipy` and `scikit-image` as latter almost always uses `scipy` functions internally. Particularly [this is true](https://github.com/scikit-image/scikit-image/blob/v0.22.0/skimage/morphology/binary.py#L144) for morphology ops

**Comment by ogencoglu** [comment]
Awesome, thanks for the swift reply!
